#!/usr/bin/env bash

create_hosts() {
  basename=$1
  for n in {0..2} ; do
    name=${basename}-${n}
    printf "\n---Create ${name}\n"
    docker-machine create -d virtualbox ${name}
  done
}

create_hosts controller
create_hosts worker

# Provisioning a CA and Generating TLS Certificates
source gencerts.sh

for instance in worker-0 worker-1 worker-2; do
  for file in ca.pem ${instance}-key.pem ${instance}.pem; do
    docker-machine scp ${file} ${instance}:~/
  done
done

for instance in controller-0 controller-1 controller-2; do
  for file in ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem; do
    docker-machine scp ${file} ${instance}:~/
  done
done

# Generating Kubernetes Configuration Files for Authentication
source generate-kubeconfigs.sh

# Bootstrapping the etcd Cluster
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md#bootstrapping-the-etcd-cluster
source install-etcd.sh
