#!/usr/bin/env bash

create_hosts() {
  basename=$1
  for n in {0..2} ; do
    name=${basename}-${n}
    printf "\n---Create ${name}\n"
    docker-machine create -d virtualbox --virtualbox-memory "2048" ${name}

    # TODO HACK This is a hack to get tce-load to install iptables/netfilter in
    # boot2docker. The boot2docker devs got cute and changed the uname.
    docker-machine ssh ${name} "sudo sed -i 's/KERNELVER=\$(uname -r)/KERNELVER=4.2.7-tinycore64/' /usr/bin/tce-load"
  done
}

create_hosts controller
create_hosts worker

# Provisioning a CA and Generating TLS Certificates
source gencerts.sh

for instance in worker-0 worker-1 worker-2; do
  for file in ca.pem ${instance}-key.pem ${instance}.pem; do
    docker-machine scp ${file} ${instance}:~/
  done
done

for instance in controller-0 controller-1 controller-2; do
  for file in ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem; do
    docker-machine scp ${file} ${instance}:~/
  done
done

# Generating Kubernetes Configuration Files for Authentication
source generate-kubeconfigs.sh

# Bootstrapping the etcd Cluster
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md#bootstrapping-the-etcd-cluster
source install-etcd.sh

# Bootstrapping the Kubernetes Control Plane
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md
source bootstrap-kubernetes-control-plane.sh

# Bootstrapping the Kubernetes Workers
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md
source bootstrap-kubernetes-workers.sh

# Configure Network Routing
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md
source network-routing.sh

# Configure Kubectl
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/10-configuring-kubectl.md
source configure-kubectl.sh

