#!/usr/bin/env bash

# Create Hosts
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-compute-resources.md
source build-hosts.sh

# Provisioning a CA and Generating TLS Certificates
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md
source gencerts.sh

# Generating Kubernetes Configuration Files for Authentication
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/05-kubernetes-configuration-files.md
source generate-kubeconfigs.sh

# Bootstrapping the etcd Cluster
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/07-bootstrapping-etcd.md#bootstrapping-the-etcd-cluster
source install-etcd.sh

# Bootstrapping the Kubernetes Control Plane
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md
source bootstrap-kubernetes-control-plane.sh

# Bootstrapping the Kubernetes Workers
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md
source bootstrap-kubernetes-workers.sh

# Configure Network Routing
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/11-pod-network-routes.md
source network-routing.sh

# Configure Kubectl
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/10-configuring-kubectl.md
source configure-kubectl.sh

# Deploy DNS
# https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/12-dns-addon.md
source deploy-kube-dns.sh
